### ISSUE TITLE
💡 [Feature] 공통 코드 관리 페이지  구현

### ISSUE THREAD

**Issue by cofls980** [project-mijeong/react-admin#9]
## 💡 기능 개요

- 공통 코드 관리 페이지  구현

## 📝 기능 상세 내용

- 공통 코드 관리 페이지  구현

## ✅ TODO

- [x] 공통 코드 조회
- [x] 공통 코드 수정
- [x] 공통 코드 생성
- [ ] 공통 코드 삭제
